[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "ruleset-engine"
version = "1.0.0"
description = "ruleset-engine validates tabular data files against data validation rules written in the RuleSet language."
requires-python = ">=3.8"
dependencies = ["textX"]

[project.scripts]
ruleset-engine = "ruleset.cli:main"

[project.entry-points.textx_languages]
ruleset = "ruleset.metamodel:ruleset_lang"

[tool.setuptools.package-data]
ruleset = ["Ruleset.tx"]